// white beld titles
export const white_titles = {
    // English
    'en': {
        'play': 'Play',
        'details': 'View Details',
        '1': 'Determination of one digit number from sequence',
        '2': 'Comparison of one-digit numbers (from 0 to 10)',
        '3': 'Addition of one-digit numbers (from 0 to 10)',
        '4': 'Subtraction of one-digit numbers (from 0 to 10)',
        '5': 'Addition and Subtraction of two one-digit numbers (from 0 to 10)',
        '6': 'Mathematical operation (Addition or Subtraction) determination',
        '7': 'Addition and Subtraction of three one-digit numbers',
        '8': 'Comparison of two expressions for one digit numbers',
        '9': 'Addition and Subtraction of two one-digit numbers (from 0 to 10)',
    },
    // Russian
    'ru': {
        'play': 'Играть',
        'details': 'Детали Игры',
        '1': 'Определение однозначного числа по последовательности',
        '2': 'Сравнение двух однозначиных чисел (от 0 до 10)',
        '3': 'Сложение двух однозначиных чисел (от 0 до 10)',
        '4': 'Вычитание двух однозначиных чисел (от 0 до 10)',
        '5': 'Сложение и Вычитание двух однозначиных чисел (от 0 до 10)',
        '6': 'Определение Математической операции (Сложение или Вычитание)',
        '7': 'Сложение и Вычитание трех однозначных чисел (от 0 до 10)',
        '8': 'Сравнение выражений двух однозначных чисел (от 0 до 10)',
        '9': 'Сложение и Вычитание двух однозначиных чисел (от 0 до 10)',
    },
    // Dutch
    'nl' : {
        'play': 'Play',
        'details': 'View Details',
        '1': 'Bepaling van een cijfer uit de reeks (van 0 tot 10)',
        '2': 'Vergelijking van getallen van een cijfer (van 0 tot 10)',
        '3': 'Optellen van getallen van een cijfer (van 0 tot 10)',
        '4': 'Aftrekken van getallen van een cijfer (van 0 tot 10)',
        '5': 'Optellen en aftrekken van twee getallen van een cijfer (van 0 tot 10)',
        '6': 'Wiskundige bewerking (optellen of aftrekken) bepaling',
        '7': 'Optellen en aftrekken van drie getallen van een cijfer',
        '8': 'Vergelijking van twee uitdrukkingen voor getallen van een cijfer',
        '9': 'Optellen en aftrekken van twee getallen van ´┐¢´┐¢n cijfer (van 0 tot 10)',
    },
    // French
    'fr' : {
        'play': 'Play',
        'details': 'View Details',
        '1': 'Determination d\'un nombre a un chiffre a partir de la sequence',
        '2': 'Comparision of one-digit numbers (from 0 to 10)',
        '3': 'Addition of one-digit numbers (from 0 to 10)',
        '4': 'Subtraction of one-digit numbers (from 0 to 10)',
        '5': 'Addition and Subtraction of two one-digit numbers (from 0 to 10)',
        '6': 'Mathematical operation (Addition or Subtraction) determination',
        '7': 'Addition and Subtraction of three one-digit numbers',
        '8': 'Comparison of two expressions for one digit numbers',
        '9': 'Addition and Subtraction of two one-digit numbers (from 0 to 10)',
    },
    // German
    'de' : {
        'play': 'Play',
        'details': 'View Details',
        '1': 'Bestimmung einer einstelligen Nummer aus der Sequenz',
        '2': 'Comparision of one-digit numbers (from 0 to 10)',
        '3': 'Addition of one-digit numbers (from 0 to 10)',
        '4': 'Subtraction of one-digit numbers (from 0 to 10)',
        '5': 'Addition and Subtraction of two one-digit numbers (from 0 to 10)',
        '6': 'Mathematical operation (Addition or Subtraction) determination',
        '7': 'Addition and Subtraction of three one-digit numbers',
        '8': 'Comparison of two expressions for one digit numbers',
        '9': 'Addition and Subtraction of two one-digit numbers (from 0 to 10)',
    },
    // Spanish
    'es' : {
        'play': 'Play',
        'details': 'View Details',
        '1': 'Determinacion del numero de un digito a partir de la secuencia.',
        '2': 'Comparision of one-digit numbers (from 0 to 10)',
        '3': 'Addition of one-digit numbers (from 0 to 10)',
        '4': 'Subtraction of one-digit numbers (from 0 to 10)',
        '5': 'Addition and Subtraction of two one-digit numbers (from 0 to 10)',
        '6': 'Mathematical operation (Addition or Subtraction) determination',
        '7': 'Addition and Subtraction of three one-digit numbers',
        '8': 'Comparison of two expressions for one digit numbers',
        '9': 'Addition and Subtraction of two one-digit numbers (from 0 to 10)',
    },
    // Italian
    'it' : {
        'play': 'Play',
        'details': 'View Details',
        '1': 'Determinazione di un numero di cifre dalla sequenza',
        '2': 'Comparision of one-digit numbers (from 0 to 10)',
        '3': 'Addition of one-digit numbers (from 0 to 10)',
        '4': 'Subtraction of one-digit numbers (from 0 to 10)',
        '5': 'Addition and Subtraction of two one-digit numbers (from 0 to 10)',
        '6': 'Mathematical operation (Addition or Subtraction) determination',
        '7': 'Addition and Subtraction of three one-digit numbers',
        '8': 'Comparison of two expressions for one digit numbers',
        '9': 'Addition and Subtraction of two one-digit numbers (from 0 to 10)',
    },
};

// white beld descriptions
export const white_descriptions = {
    // English
    'en': {
        '1': 'Tasks for one-digit numbers (from 0 to 9) sequences, where kids have three consecutive numbers (for example: 1, 2, 3) and have to understand the next (fourth - 4). The last number displayed with questionmark. Number sequences can be ascending (example, 4-5-6-?) and descending (example, 5-4-3-?)',
        '2': 'Tasks for Comparision of one-digit numbers (from 0 to 9), where kids can use only three operations: more (>), less (<) and equal (=). There are two one digit numbers displayed with questionmark in between',
        '3': 'Tasks for Addition of one-digit numbers. Kids have to add two simple one digit numbers, where the result of addition can be an one (example, 2+2=4) or two digit number (9+9=18)',
        '4': 'Tasks for Subtraction of one-digit numbers. The result of subtraction can be is zero (example, 3-3=0) or a one-digit number (example, 8-4=5)',
        '5': 'Tasks for Addition and Subtraction of two one-digit numbers. The result of addition can be an one or two digit number, the result of subtraction is zero or a one-digit number',
        '6': 'Tasks for Math operation determination: Addition (+) or Subtraction (-). Kids have two one digit numbers (from 1 to 10, zero is excluded from range) and result of a math operation with that numbers. Based on operation result, they have to understand what it was: Addition (+) or Subtraction (-). For example, 4 ? 5 = 9, operation is Plus (+)',
        '7': 'Tasks for Addition and Subtraction of three one-digit numbers. The result of addition can be an one (example, 1+1+1=3) or two digit number (example, 7+8+9=24), the result of subtraction can be zero (example, 9-5-4=0) or a one-digit number (example, 8-1-1=6)',
        '8': 'Tasks for results Comparision of two arithmetic expressions each of one consists from two one-digit numbers (3+4 and 9-2) and one mathematical operation: plus or minus. Kids have to solve both expressions in mind and select one of the appropriate operation: more (>), less (<) and equal (=). The result of each expression can be zero, one or two digit number',
        '9': 'Tasks for Addition and Subtraction of two one-digit numbers, where kids know only one of the argument and result of math task. Based on mathematical operation they have to find another argument. For example, 6 + ? = 9 (results is 3) OR 7 - ? = 0 (result is 0)',
    },
    // Russian
    'ru': {
        '1': 'Tasks for one-digit numbers (from 0 to 9) sequences, where kids have three consecutive numbers (for example: 1, 2, 3) and have to understand the next (fourth - 4). The last number displayed with questionmark. Number sequences can be ascending (example, 4-5-6-?) and descending (example, 5-4-3-?)',
        '2': 'Tasks for Comparision of one-digit numbers (from 0 to 9), where kids can use only three operations: more (>), less (<) and equal (=). There are two one digit numbers displayed with questionmark in between',
        '3': 'Tasks for Addition of one-digit numbers. Kids have to add two simple one digit numbers, where the result of addition can be an one (example, 2+2=4) or two digit number (9+9=18)',
        '4': 'Tasks for Subtraction of one-digit numbers. The result of subtraction can be is zero (example, 3-3=0) or a one-digit number (example, 8-4=5)',
        '5': 'Tasks for Addition and Subtraction of two one-digit numbers. The result of addition can be an one or two digit number, the result of subtraction is zero or a one-digit number',
        '6': 'Tasks for Math operation determination: Addition (+) or Subtraction (-). Kids have two one digit numbers (from 1 to 10, zero is excluded from range) and result of a math operation with that numbers. Based on operation result, they have to understand what it was: Addition (+) or Subtraction (-). For example, 4 ? 5 = 9, operation is Plus (+)',
        '7': 'Tasks for Addition and Subtraction of three one-digit numbers. The result of addition can be an one (example, 1+1+1=3) or two digit number (example, 7+8+9=24), the result of subtraction can be zero (example, 9-5-4=0) or a one-digit number (example, 8-1-1=6)',
        '8': 'Tasks for results Comparision of two arithmetic expressions each of one consists from two one-digit numbers (3+4 and 9-2) and one mathematical operation: plus or minus. Kids have to solve both expressions in mind and select one of the appropriate operation: more (>), less (<) and equal (=). The result of each expression can be zero, one or two digit number',
        '9': 'Tasks for Addition and Subtraction of two one-digit numbers, where kids know only one of the argument and result of math task. Based on mathematical operation they have to find another argument. For example, 6 + ? = 9 (results is 3) OR 7 - ? = 0 (result is 0)',
    },
    // Dutch
    'nl' : {
        '1': 'Tasks for one-digit numbers (from 0 to 9) sequences, where kids have three consecutive numbers (for example: 1, 2, 3) and have to understand the next (fourth - 4). The last number displayed with questionmark. Number sequences can be ascending (example, 4-5-6-?) and descending (example, 5-4-3-?)',
        '2': 'Tasks for Comparision of one-digit numbers (from 0 to 9), where kids can use only three operations: more (>), less (<) and equal (=). There are two one digit numbers displayed with questionmark in between',
        '3': 'Tasks for Addition of one-digit numbers. Kids have to add two simple one digit numbers, where the result of addition can be an one (example, 2+2=4) or two digit number (9+9=18)',
        '4': 'Tasks for Subtraction of one-digit numbers. The result of subtraction can be is zero (example, 3-3=0) or a one-digit number (example, 8-4=5)',
        '5': 'Tasks for Addition and Subtraction of two one-digit numbers. The result of addition can be an one or two digit number, the result of subtraction is zero or a one-digit number',
        '6': 'Tasks for Math operation determination: Addition (+) or Subtraction (-). Kids have two one digit numbers (from 1 to 10, zero is excluded from range) and result of a math operation with that numbers. Based on operation result, they have to understand what it was: Addition (+) or Subtraction (-). For example, 4 ? 5 = 9, operation is Plus (+)',
        '7': 'Tasks for Addition and Subtraction of three one-digit numbers. The result of addition can be an one (example, 1+1+1=3) or two digit number (example, 7+8+9=24), the result of subtraction can be zero (example, 9-5-4=0) or a one-digit number (example, 8-1-1=6)',
        '8': 'Tasks for results Comparision of two arithmetic expressions each of one consists from two one-digit numbers (3+4 and 9-2) and one mathematical operation: plus or minus. Kids have to solve both expressions in mind and select one of the appropriate operation: more (>), less (<) and equal (=). The result of each expression can be zero, one or two digit number',
        '9': 'Tasks for Addition and Subtraction of two one-digit numbers, where kids know only one of the argument and result of math task. Based on mathematical operation they have to find another argument. For example, 6 + ? = 9 (results is 3) OR 7 - ? = 0 (result is 0)',
    },
    // French
    'fr' : {
        '1': 'Tasks for one-digit numbers (from 0 to 9) sequences, where kids have three consecutive numbers (for example: 1, 2, 3) and have to understand the next (fourth - 4). The last number displayed with questionmark. Number sequences can be ascending (example, 4-5-6-?) and descending (example, 5-4-3-?)',
        '2': 'Tasks for Comparision of one-digit numbers (from 0 to 9), where kids can use only three operations: more (>), less (<) and equal (=). There are two one digit numbers displayed with questionmark in between',
        '3': 'Tasks for Addition of one-digit numbers. Kids have to add two simple one digit numbers, where the result of addition can be an one (example, 2+2=4) or two digit number (9+9=18)',
        '4': 'Tasks for Subtraction of one-digit numbers. The result of subtraction can be is zero (example, 3-3=0) or a one-digit number (example, 8-4=5)',
        '5': 'Tasks for Addition and Subtraction of two one-digit numbers. The result of addition can be an one or two digit number, the result of subtraction is zero or a one-digit number',
        '6': 'Tasks for Math operation determination: Addition (+) or Subtraction (-). Kids have two one digit numbers (from 1 to 10, zero is excluded from range) and result of a math operation with that numbers. Based on operation result, they have to understand what it was: Addition (+) or Subtraction (-). For example, 4 ? 5 = 9, operation is Plus (+)',
        '7': 'Tasks for Addition and Subtraction of three one-digit numbers. The result of addition can be an one (example, 1+1+1=3) or two digit number (example, 7+8+9=24), the result of subtraction can be zero (example, 9-5-4=0) or a one-digit number (example, 8-1-1=6)',
        '8': 'Tasks for results Comparision of two arithmetic expressions each of one consists from two one-digit numbers (3+4 and 9-2) and one mathematical operation: plus or minus. Kids have to solve both expressions in mind and select one of the appropriate operation: more (>), less (<) and equal (=). The result of each expression can be zero, one or two digit number',
        '9': 'Tasks for Addition and Subtraction of two one-digit numbers, where kids know only one of the argument and result of math task. Based on mathematical operation they have to find another argument. For example, 6 + ? = 9 (results is 3) OR 7 - ? = 0 (result is 0)',
    },
    // German
    'de' : {
        '1': 'Tasks for one-digit numbers (from 0 to 9) sequences, where kids have three consecutive numbers (for example: 1, 2, 3) and have to understand the next (fourth - 4). The last number displayed with questionmark. Number sequences can be ascending (example, 4-5-6-?) and descending (example, 5-4-3-?)',
        '2': 'Tasks for Comparision of one-digit numbers (from 0 to 9), where kids can use only three operations: more (>), less (<) and equal (=). There are two one digit numbers displayed with questionmark in between',
        '3': 'Tasks for Addition of one-digit numbers. Kids have to add two simple one digit numbers, where the result of addition can be an one (example, 2+2=4) or two digit number (9+9=18)',
        '4': 'Tasks for Subtraction of one-digit numbers. The result of subtraction can be is zero (example, 3-3=0) or a one-digit number (example, 8-4=5)',
        '5': 'Tasks for Addition and Subtraction of two one-digit numbers. The result of addition can be an one or two digit number, the result of subtraction is zero or a one-digit number',
        '6': 'Tasks for Math operation determination: Addition (+) or Subtraction (-). Kids have two one digit numbers (from 1 to 10, zero is excluded from range) and result of a math operation with that numbers. Based on operation result, they have to understand what it was: Addition (+) or Subtraction (-). For example, 4 ? 5 = 9, operation is Plus (+)',
        '7': 'Tasks for Addition and Subtraction of three one-digit numbers. The result of addition can be an one (example, 1+1+1=3) or two digit number (example, 7+8+9=24), the result of subtraction can be zero (example, 9-5-4=0) or a one-digit number (example, 8-1-1=6)',
        '8': 'Tasks for results Comparision of two arithmetic expressions each of one consists from two one-digit numbers (3+4 and 9-2) and one mathematical operation: plus or minus. Kids have to solve both expressions in mind and select one of the appropriate operation: more (>), less (<) and equal (=). The result of each expression can be zero, one or two digit number',
        '9': 'Tasks for Addition and Subtraction of two one-digit numbers, where kids know only one of the argument and result of math task. Based on mathematical operation they have to find another argument. For example, 6 + ? = 9 (results is 3) OR 7 - ? = 0 (result is 0)',
    },
    // Spanish
    'es' : {
        '1': 'Tasks for one-digit numbers (from 0 to 9) sequences, where kids have three consecutive numbers (for example: 1, 2, 3) and have to understand the next (fourth - 4). The last number displayed with questionmark. Number sequences can be ascending (example, 4-5-6-?) and descending (example, 5-4-3-?)',
        '2': 'Tasks for Comparision of one-digit numbers (from 0 to 9), where kids can use only three operations: more (>), less (<) and equal (=). There are two one digit numbers displayed with questionmark in between',
        '3': 'Tasks for Addition of one-digit numbers. Kids have to add two simple one digit numbers, where the result of addition can be an one (example, 2+2=4) or two digit number (9+9=18)',
        '4': 'Tasks for Subtraction of one-digit numbers. The result of subtraction can be is zero (example, 3-3=0) or a one-digit number (example, 8-4=5)',
        '5': 'Tasks for Addition and Subtraction of two one-digit numbers. The result of addition can be an one or two digit number, the result of subtraction is zero or a one-digit number',
        '6': 'Tasks for Math operation determination: Addition (+) or Subtraction (-). Kids have two one digit numbers (from 1 to 10, zero is excluded from range) and result of a math operation with that numbers. Based on operation result, they have to understand what it was: Addition (+) or Subtraction (-). For example, 4 ? 5 = 9, operation is Plus (+)',
        '7': 'Tasks for Addition and Subtraction of three one-digit numbers. The result of addition can be an one (example, 1+1+1=3) or two digit number (example, 7+8+9=24), the result of subtraction can be zero (example, 9-5-4=0) or a one-digit number (example, 8-1-1=6)',
        '8': 'Tasks for results Comparision of two arithmetic expressions each of one consists from two one-digit numbers (3+4 and 9-2) and one mathematical operation: plus or minus. Kids have to solve both expressions in mind and select one of the appropriate operation: more (>), less (<) and equal (=). The result of each expression can be zero, one or two digit number',
        '9': 'Tasks for Addition and Subtraction of two one-digit numbers, where kids know only one of the argument and result of math task. Based on mathematical operation they have to find another argument. For example, 6 + ? = 9 (results is 3) OR 7 - ? = 0 (result is 0)',
    },
    // Italian
    'it' : {
        '1': 'Tasks for one-digit numbers (from 0 to 9) sequences, where kids have three consecutive numbers (for example: 1, 2, 3) and have to understand the next (fourth - 4). The last number displayed with questionmark. Number sequences can be ascending (example, 4-5-6-?) and descending (example, 5-4-3-?)',
        '2': 'Tasks for Comparision of one-digit numbers (from 0 to 9), where kids can use only three operations: more (>), less (<) and equal (=). There are two one digit numbers displayed with questionmark in between',
        '3': 'Tasks for Addition of one-digit numbers. Kids have to add two simple one digit numbers, where the result of addition can be an one (example, 2+2=4) or two digit number (9+9=18)',
        '4': 'Tasks for Subtraction of one-digit numbers. The result of subtraction can be is zero (example, 3-3=0) or a one-digit number (example, 8-4=5)',
        '5': 'Tasks for Addition and Subtraction of two one-digit numbers. The result of addition can be an one or two digit number, the result of subtraction is zero or a one-digit number',
        '6': 'Tasks for Math operation determination: Addition (+) or Subtraction (-). Kids have two one digit numbers (from 1 to 10, zero is excluded from range) and result of a math operation with that numbers. Based on operation result, they have to understand what it was: Addition (+) or Subtraction (-). For example, 4 ? 5 = 9, operation is Plus (+)',
        '7': 'Tasks for Addition and Subtraction of three one-digit numbers. The result of addition can be an one (example, 1+1+1=3) or two digit number (example, 7+8+9=24), the result of subtraction can be zero (example, 9-5-4=0) or a one-digit number (example, 8-1-1=6)',
        '8': 'Tasks for results Comparision of two arithmetic expressions each of one consists from two one-digit numbers (3+4 and 9-2) and one mathematical operation: plus or minus. Kids have to solve both expressions in mind and select one of the appropriate operation: more (>), less (<) and equal (=). The result of each expression can be zero, one or two digit number',
        '9': 'Tasks for Addition and Subtraction of two one-digit numbers, where kids know only one of the argument and result of math task. Based on mathematical operation they have to find another argument. For example, 6 + ? = 9 (results is 3) OR 7 - ? = 0 (result is 0)',
    },
};
